apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooocus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fooocus
  strategy:
    # We have only one GPU, so we have to be disruptive in this demo.
    type: Recreate
  template:
    metadata:
      labels:
        app: fooocus
        ai.gke.io/inference-server: fooocus
    spec:
      # required so the sidecar instrumenter can access the service process
      shareProcessNamespace: true
      containers:
      - name: inference-server
        # https://github.com/mrhan1993/Fooocus-API
        # https://hub.docker.com/r/konieshadow/fooocus-api/tags
        image: konieshadow/fooocus-api:v0.3.30 # Serves on 8888 port.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        # On the initial start, the app is installing deps and models, embrace patience.
        readinessProbe:
          httpGet:
            path: /ping
            port: 8888
          periodSeconds: 5
          failureThreshold: 240 # Wait 20m max.
        resources:
          requests:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "20Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "20Gi"
            ephemeral-storage: "20Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      # Derived from https://github.com/grafana/beyla/blob/main/deployments/03-instrumented-app.yml
      - name: autoinstrumenter
        image: grafana/beyla:1.3.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9400
        - containerPort: 9401
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /config
          name: beyla-config
        - mountPath: /sys/kernel/security
          name: system-config
        env:
        - name: BEYLA_CONFIG_PATH
          value: "/config/beyla-config.yml"
        - name: BEYLA_SERVICE_NAME
          value: "fooocus"
        - name: BEYLA_OPEN_PORT
          value: "8888"
        - name: BEYLA_PROMETHEUS_PORT
          value: "9400"
        - name: BEYLA_INTERNAL_METRICS_PROMETHEUS_PORT
          value: "9401"
        - name: BEYLA_LOG_LEVEL
          value: "DEBUG"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: beyla-config
        configMap:
          name: beyla-config
      - name: system-config
        configMap:
          name: system-config
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: fooocus
spec:
  selector:
    app: fooocus
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: fooocus
  labels:
    app: fooocus
spec:
  selector:
    matchLabels:
      app: fooocus
  endpoints:
  - port: 9400
    interval: 15s
    metricRelabeling:
    - regex: >
        service_namespace|service_name
      action: labeldrop
  - port: 9401
    path: "/internal/metrics"
    interval: 15s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: system-config
data:
  lockdown: none [integrity] confidentiality
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    routes:
      unmatched: heuristic
