apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooocus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fooocus
  strategy:
    # We have only one GPU, so we have to be disruptive in this demo.
    type: Recreate
  template:
    metadata:
      labels:
        app: fooocus
        ai.gke.io/inference-server: fooocus
    spec:
      containers:
      - name: inference-server
        # https://github.com/ashleykleynhans/fooocus-docker
        # https://hub.docker.com/r/ashleykza/fooocus/tags
        image: ashleykza/fooocus:2.2.1
        resources:
          requests:
            cpu: "2"
            memory: "10Gi"
            ephemeral-storage: "20Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "20Gi"
            ephemeral-storage: "20Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: fooocus
spec:
  selector:
    app: fooocus
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
